lst = list(range(10,101,10))
hwlst=list('Hello, World!')
lenlst=len(lst)
n= lst.index(20)
c=lst.count(30)
s=sum(lst)
t =list(map(lambda x: x*x, lst))
print(lst)
print(lenlst)
print('Die Anzahl an Werten in der Liste betraegt' ,lenlst)
print('An der {}. Stelle kommt die 20 in der Liste vor' .format(n +1))
print('Die Zahl sagt wie oft die 30 vorkommt' ,c)
print('Die Summe betraegt' ,s)
print(t)
print(lst[2:4])
print(lst[0:4])
print(hwlst)
print(hwlst[0:4])
print(''.join(hwlst))